- name: Debug host path
  ansible.builtin.debug:
    msg: "HOST_APP_PATH = {{ lookup('env', 'HOST_APP_PATH') }}"

- name: Stop and remove existing webapp container
  ansible.builtin.command: docker rm -f webapp
  changed_when: false
  failed_when: false

- name: Run nginx container
  ansible.builtin.command: >
    docker run -d --name webapp -p {{ app_port }}:80 -v {{ lookup('env',
    'HOST_APP_PATH') }}:/usr/share/nginx/html:ro nginx:alpine
  changed_when: true
